FROM oven/bun AS build
WORKDIR /app
# Cache packages installation
COPY . .
RUN bun install

ENV NODE_ENV=production
RUN bun run prisma:generate
RUN bun run build

FROM gcr.io/distroless/base AS backend
WORKDIR /app
COPY --from=build /app/packages/backend/server server

ENV NODE_ENV=production

CMD ["./server"]

EXPOSE 8090